### ISSUE TITLE
Merge Admin Branch & Branch #2

### ISSUE THREAD

**Issue by paulenepal** [paulenepal/pet-network-app#4]

**Comment by Menard-S** [comment]
Hello everyone,

Invitable mailer + link now working for both Adopter and Shelter!
![mailers](https://github.com/paulenepal/pet-network-app/assets/143720039/9802c786-62b3-45fc-84d3-667aaf331a8f)

Account creation form for the invited users now working as well.  You can see both users in their corresponding tables below:
![user](https://github.com/paulenepal/pet-network-app/assets/143720039/c95d10d3-ec34-42e6-b96e-565754af461f)
![jr shelter](https://github.com/paulenepal/pet-network-app/assets/143720039/e591d6a8-93b5-49df-aa8c-27ed2de542fe)
com/paulenepal/pet-network-app/assets/143720039/5ae94975-d1c4-4217-a0a1-2f98e4c115b7)
![adopter](https://github.com/paulenepal/pet-network-app/assets/143720039/1c6d8b2e-9fe2-4002-aa21-fc0c235c21f5)

Since for some reason the Devise cannot map the route within the context of the invitable mailer, I decided to use url_helpers in the application_mailer.rb:
![path](https://github.com/paulenepal/pet-network-app/assets/143720039/667d5472-89af-4d91-bffe-65df9fb92820)

For routes.rb, no changes implemented except "devise_scope." For users/registrations_controller, only methods related to invitable were modifed (i.e., new_invited_user and create_invited_user).

Thank you!
